In [1]:
import numpy as np
import pylab as pl
import pandas as pd
import matplotlib.pyplot as plt 
%matplotlib inline
import seaborn as sns
from sklearn.utils import shuffle
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestRegressor
import os
print(os.listdir("C:/Users/Admin/OneDrive/Desktop/leaves28"))

['black spot', 'canker', 'greening', 'healthy', 'melanose']


In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load the data from the CSV file
data = pd.read_csv('leaf__data.csv')

# Separate the features (X) from the labels (y)
X = data.drop('disease', axis=1)
y = data['disease']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



In [27]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
y_train=lb.fit_transform(y_train)
y_test=lb.fit_transform(y_test)


In [28]:
from sklearn.model_selection import KFold
kfold_validation=KFold(10)

# LSVM

In [29]:
from sklearn.svm import SVC  
svm = SVC(kernel='linear') 

svm.fit(X_train, y_train)

y_pred_svm=svm.predict(X_test)
y_pred_svm

accuracy_svm = accuracy_score(y_test, y_pred_svm)

print('Accuracy:', accuracy_svm*100)


Accuracy: 86.93181818181817


# CONFUSION MATRIX

In [52]:
cm = confusion_matrix(y_pred_svm, y_test)

cm

array([[26,  0,  2,  7,  2],
       [ 0, 48,  0,  1,  0],
       [ 1,  1, 34,  1,  0],
       [ 6,  0,  0, 38,  0],
       [ 2,  0,  0,  0,  7]], dtype=int64)

In [31]:
print(classification_report(y_pred_svm,y_test))

              precision    recall  f1-score   support

           0       0.74      0.70      0.72        37
           1       0.98      0.98      0.98        49
           2       0.94      0.92      0.93        37
           3       0.81      0.86      0.84        44
           4       0.78      0.78      0.78         9

    accuracy                           0.87       176
   macro avg       0.85      0.85      0.85       176
weighted avg       0.87      0.87      0.87       176



# USING KFOLD CROSS VALIDATION

In [44]:
from sklearn.model_selection import cross_val_score
acc1=[]
accuracies = cross_val_score(estimator = svm, X = X_train, y = y_train, cv = 10)
for x in accuracies:
    acc1.append(x)
print(acc1)
print('Average accuracy after KFold cross validation : ',accuracies.mean())

[0.8571428571428571, 0.8857142857142857, 0.7, 0.8714285714285714, 0.8, 0.8714285714285714, 0.8571428571428571, 0.8571428571428571, 0.8428571428571429, 0.8428571428571429]
Average accuracy after KFold cross validation :  0.8385714285714284


 # RANDOM FOREST 

In [45]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=40, random_state=40)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

from sklearn.metrics import accuracy_score
print('Accuracy:', accuracy_score(y_test, y_pred_rf)*100)


Accuracy: 84.6590909090909


In [51]:
cm1 = confusion_matrix(y_pred_rf,y_test)

cm1

array([[26,  0,  1,  9,  0],
       [ 0, 49,  0,  0,  0],
       [ 0,  0, 32,  1,  1],
       [ 7,  0,  2, 37,  3],
       [ 2,  0,  1,  0,  5]], dtype=int64)

# USING KFOLD FOR RF

In [54]:
acc2=[]
accuracies = cross_val_score(estimator = rf, X = X_train, y = y_train, cv = 10)
for x in accuracies:
    acc2.append(x)
print(acc2)
print('Average accuracy after KFold cross validation : ',accuracies.mean())

[0.8571428571428571, 0.8857142857142857, 0.7714285714285715, 0.8142857142857143, 0.8, 0.9714285714285714, 0.9142857142857143, 0.9285714285714286, 0.8285714285714286, 0.8428571428571429]
Average accuracy after KFold cross validation :  0.8614285714285714


# STOCHASTIC GRADIENT DESCENT

In [55]:
from sklearn.linear_model import SGDClassifier

sgd = SGDClassifier(loss='hinge', penalty='l2', alpha=0.1, max_iter=1000, eta0=0.1, learning_rate='optimal', random_state=30)

sgd.fit(X_train, y_train)

y_pred_sgd = sgd.predict(X_test)

accuracy_sgd = accuracy_score(y_test, y_pred_sgd)

print('Accuracy:', accuracy_sgd*100)


Accuracy: 75.0


In [56]:
cm2 = confusion_matrix(y_pred_sgd,y_test)

cm2

array([[23,  0,  6,  9,  1],
       [ 0, 48,  7,  0,  0],
       [ 0,  1, 17,  0,  0],
       [12,  0,  3, 36,  0],
       [ 0,  0,  3,  2,  8]], dtype=int64)

# USING KFOLD FOR SGD

In [57]:
acc3=[]
accuracies = cross_val_score(estimator = sgd, X = X_train, y = y_train, cv = 10)
for x in accuracies:
    acc3.append(x)
print(acc3)
print('Average accuracy after KFold cross validation : ',accuracies.mean())

[0.7142857142857143, 0.7285714285714285, 0.6714285714285714, 0.7571428571428571, 0.7142857142857143, 0.8142857142857143, 0.7, 0.7714285714285715, 0.7857142857142857, 0.6714285714285714]
Average accuracy after KFold cross validation :  0.7328571428571429


 # LOGISTIC REGRESSION

In [58]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(penalty='l2', random_state=50, max_iter=100)

lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

accuracy_lr = accuracy_score(y_test, y_pred_lr)

print('Accuracy:', accuracy_lr*100)


C:\Users\Admin\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


Accuracy: 86.36363636363636


In [59]:
cm3 = confusion_matrix(y_pred_lr,y_test)

cm3

array([[23,  0,  1,  6,  1],
       [ 0, 48,  0,  0,  0],
       [ 1,  1, 34,  0,  0],
       [11,  0,  0, 39,  0],
       [ 0,  0,  1,  2,  8]], dtype=int64)